const styles = {
  passport_container: {
    width: "260px",
    height: "387px",
    border: "1px solid #888888",
    borderRadius: "4.58071px 61.3816px 4.58071px 4.58071px",
    marginLeft: "5px",
    padding: "10px 23px",
  },
  title: {
    textAlign: "left",
    fontWeight: "700",
    fontSize: "12px",
    textTransform: "uppercase",
    color: "#888888",
    lineHeight: "18px",
    letterSpacing: "0.1em",
  },
  passport: {
    textAlign: "left",
    fontWeight: "700",
    fontSize: "28px",
    lineHeight: "27px",
    letterSpacing: "0.1em",
    textTransform: "uppercase",
    color: "#F6F6F6",
  },
  date: {
    textAlign: "left",
    fontWeight: "700",
    fontSize: "10px",
    lineHeight: "12px",
    letterSpacing: "0.1em",
    textTransform: "uppercase",
    color: "#888888",
    margin: "7px 0",
  },
  image_container: {
    width: "100%",
    height: "200px",
    border: "0.6413px solid #6A6A6A",
    borderRadius: "4.58071px",
  },
  passport_image: {
    width: "120px",
    height: "120px",
  },
  hr: {
    marginTop: "13px",
    width: "100%",
    height: "1px",
    backgroundColor: "#888888",
  },
  decoder_container: {
    marginTop: "12px",
    width: "100%",
  },
  lock_image: {
    marginRight: "5px",
  },
  decoder_text: {
    fontWeight: "600",
    fontSize: "16px",
    lineHeight: "20px",
    textTransform: "uppercase",
  },
  survival_text: {
    marginTop: "12px",
    fontWeight: "700",
    fontSize: "12px",
    lineHeight: "15px",
    letterSpacing: "0.1em",
    textTransform: "uppercase",
    color: "#888888",
    textAlign: "left",
  },
  assessment_text: {
    textAlign: "left",
    fontWeight: "700",
    fontSize: "28px",
    lineHeight: "27px",
    letterSpacing: "0.1em",
    textTransform: "uppercase",
    color: "#e6b2b9",
  },
  rank_text: {
    fontWeight: "400",
    fontSize: "11px",
    lineHeight: "15px",
    textAlign: "left",
    color: "#F6F6F6",
  },
  progress_container: {
    width: "93%",
    position: "relative",
    paddingLeft: "2px",
  },
  exp_track: {
    background: "#000000",
    borderRadius: "94.854px",
    width: "100%",
    height: "7px",
    marginRight: "10px",
  },
  xp_numbers: {
    fontWeight: "400",
    fontSize: "11px",
    lineHeight: "15px",
    textAlign: "left",
    color: "#F6F6F6",
  },
};

export default styles;
